fix

diff --git a/.github/workflows/PreviewVercelDeploy.yaml b/.github/workflows/PreviewVercelDeploy.yaml
--- a/.github/workflows/PreviewVercelDeploy.yaml
+++ b/.github/workflows/PreviewVercelDeploy.yaml
@@ -109,28 +109,28 @@ jobs:
       - name: Install Playwright Browsers (app-keystone)
         run: docker compose exec app-keystone npx playwright install --with-deps
 
-      - name: Show Keystone logs
-        run: docker compose logs app-keystone
+      # - name: Show Keystone logs
+      #   run: docker compose logs app-keystone
 
-      - name: Wait for Keystone to be ready
-        run: |
-          for i in {1..30}; do
-            if docker compose exec app-keystone curl -s http://localhost:3000 > /dev/null; then
-              echo "Keystone is up!"
-              exit 0
-            fi
-            echo "Waiting for Keystone..."
-            sleep 2
-          done
-          echo "Keystone did not start in time"
-          exit 1
+      # - name: Wait for Keystone to be ready
+      #   run: |
+      #     for i in {1..30}; do
+      #       if docker compose exec app-keystone curl -s http://localhost:3000 > /dev/null; then
+      #         echo "Keystone is up!"
+      #         exit 0
+      #       fi
+      #       echo "Waiting for Keystone..."
+      #       sleep 2
+      #     done
+      #     echo "Keystone did not start in time"
+      #     exit 1
 
-      - name: Show Keystone logs
-        run: docker compose logs app-keystone
+      # - name: Show Keystone logs
+      #   run: docker compose logs app-keystone
 
       - name: Run Playwright tests (app-keystone)
         run: |
-          docker compose exec app-keystone sh -c "npm run test:e2e -- e2e/keystone-test" || echo "TESTS_FAILED=true" >> $GITHUB_ENV
+          timeout 600s docker compose exec app-keystone sh -c "npm run test:e2e -- e2e/keystone-test" || echo "TESTS_FAILED=true" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: Install Playwright Browsers (app-nextjs)
@@ -142,7 +142,7 @@ jobs:
 
       - name: Run Playwright tests (app-nextjs)
         run: |
-          docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test" || echo "TESTS_FAILED=true" >> $GITHUB_ENV
+          timeout 600s docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test" || echo "TESTS_FAILED=true" >> $GITHUB_ENV
         continue-on-error: true
 
       - uses: actions/upload-artifact@v4
