Changed pipeline code

diff --git a/.github/workflows/PreviewVercelDeploy.yaml b/.github/workflows/PreviewVercelDeploy.yaml
--- a/.github/workflows/PreviewVercelDeploy.yaml
+++ b/.github/workflows/PreviewVercelDeploy.yaml
@@ -67,16 +67,20 @@ jobs:
         run: docker compose exec app-keystone npx playwright install --with-deps
 
       - name: Run Playwright tests (app-keystone)
-        run: docker compose exec app-keystone sh -c "npm run test:e2e -- e2e/keystone-test"
+        run: |
+          set -e  # Ensures failure stops the pipeline
+          docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/keystone-test"
 
       - name: Install Playwright Browsers (app-nextjs)
         run: docker compose exec app-nextjs npx playwright install --with-deps
 
       - name: Run Playwright tests (app-nextjs)
-        run: docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test"
+        run: |
+          set -e  # Ensures failure stops the pipeline
+          docker compose exec app-nextjs sh -c "npm run test:e2e -- e2e/nextjs-test"
 
       - uses: actions/upload-artifact@v4
-        if: ${{ !cancelled() }}
+        if: ${{ success() }}
         with:
           name: playwright-report
           path: veterans/playwright-report/
