fix

diff --git a/.github/workflows/VercelDeploy.yaml b/.github/workflows/VercelDeploy.yaml
--- a/.github/workflows/VercelDeploy.yaml
+++ b/.github/workflows/VercelDeploy.yaml
@@ -67,36 +67,36 @@ jobs:
       - name: Show schema.prisma content in node modules
         run: cat ./veterans/node_modules/.prisma/client/schema.prisma
 
-      # - name: Pull Vercel Environment
-      #   run: |
-      #     npx vercel pull --yes --environment=preview --token="$VERCEL_CLI_TOKEN"
-      #     echo "Vercel Environment pulled successfully."
+      - name: Pull Vercel Environment
+        run: |
+          npx vercel pull --yes --environment=preview --token="$VERCEL_CLI_TOKEN"
+          echo "Vercel Environment pulled successfully."
 
-      # - name: Build project
-      #   run: npx vercel build --yes --token="$VERCEL_CLI_TOKEN"
-      #   timeout-minutes: 10
-      #   working-directory: ./veterans
+      - name: Build project
+        run: npx vercel build --yes --token="$VERCEL_CLI_TOKEN"
+        timeout-minutes: 10
+        working-directory: ./veterans
 
-      # - name: Deploy to Vercel
-      #   id: deploy
-      #   run: |
-      #     if ! DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --token="$VERCEL_CLI_TOKEN"); then
-      #       echo "::error::Deployment failed"
-      #       exit 1
-      #     fi
-      #     echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> "$GITHUB_ENV"
-      #   timeout-minutes: 10
-      #   working-directory: ./veterans
+      - name: Deploy to Vercel
+        id: deploy
+        run: |
+          if ! DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --token="$VERCEL_CLI_TOKEN"); then
+            echo "::error::Deployment failed"
+            exit 1
+          fi
+          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> "$GITHUB_ENV"
+        timeout-minutes: 10
+        working-directory: ./veterans
 
-      # - name: Check if DEPLOYMENT_URL is set
-      #   run: |
-      #     if [ -z "${{ env.DEPLOYMENT_URL }}" ]; then
-      #       echo "::error::DEPLOYMENT_URL is not set. This might be due to:"
-      #       echo "1. Failed Vercel deployment"
-      #       echo "2. Missing or invalid VERCEL_CLI_TOKEN"
-      #       echo "3. Network connectivity issues"
-      #       echo "Please check the deployment logs above for more details."
-      #       exit 1
-      #     else
-      #       echo "DEPLOYMENT_URL is set to: ${{ env.DEPLOYMENT_URL }}"
-      #     fi
+      - name: Check if DEPLOYMENT_URL is set
+        run: |
+          if [ -z "${{ env.DEPLOYMENT_URL }}" ]; then
+            echo "::error::DEPLOYMENT_URL is not set. This might be due to:"
+            echo "1. Failed Vercel deployment"
+            echo "2. Missing or invalid VERCEL_CLI_TOKEN"
+            echo "3. Network connectivity issues"
+            echo "Please check the deployment logs above for more details."
+            exit 1
+          else
+            echo "DEPLOYMENT_URL is set to: ${{ env.DEPLOYMENT_URL }}"
+          fi
